<?php

return \Expansa\Facades\Form::enqueue(
    'system-install',
    [
        'class'           => 'dg g-2',
        '@submit.prevent' => '$ajax.post("system/install").then(() => goto(5))',
        'u-data'          => '{...step, compat: {}, isCompatible: false}',
    ],
    [
        [
            'type'       => 'step',
            'attributes' => [
                'class'           => 'dg g-8 pt-8',
                'u-step.required' => '',
            ],
            'fields'     => [
                [
                    'type'        => 'header',
                    'label'       => t('Welcome to Expansa!'),
                    'name'        => 'title',
                    'class'       => 't-center',
                    'instruction' => t('This is the installation wizard. Before you begin, please fill in some information about your website.'),
                    'attributes'  => [ 'u-prop' => 'title' ],
                ],
                [
                    'name'  => 'website-data',
                    'type'  => 'divider',
                    'label' => t('Website data'),
                    'attributes'  => [ 'u-prop' => 'websiteData' ],
                ],
                [
                    'type'        => 'text',
                    'name'        => 'site[name]',
                    'label'       => t('Site name'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => '',
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'u-prop'         => 'site.name',
                        'placeholder'    => t('Example: My Blog'),
                        'required'       => true,
                        'u-autocomplete' => '',
                    ],
                ],
                [
                    'type'        => 'text',
                    'name'        => 'site[tagline]',
                    'label'       => t('Site tagline'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => t("Don't worry, you can always change these settings later"),
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'u-prop'         => 'site.tagline',
                        'placeholder'    => t('Example: Just another Expansa site'),
                        'u-autocomplete' => '',
                    ],
                ]
            ],
        ],
        [
            'type'       => 'step',
            'attributes' => [
                'class'           => 'dg g-8 pt-8',
                'hidden'          => true,
                'u-step.required' => '',
                'u-step:action'   => 'compat = {}; isCompatible = false',
            ],
            'fields'     => [
                [
                    'name'        => 'title',
                    'type'        => 'header',
                    'label'       => t('Step 1: Database'),
                    'instruction' => t('Enter your database connection details. If you\'re not sure what they are, contact your hosting provider.'),
                    'attributes'  => [
						'u-prop' => 'title',
                    ],
                ],
                [
                    'name'        => 'credits',
                    'type'        => 'divider',
                    'label'       => t('Database credentials'),
                    'attributes'  => [
						'u-prop' => 'credits',
                    ],
                ],
                [
                    'type'        => 'text',
                    'name'        => 'db[database]',
                    'label'       => t('Database name'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => t('Enter the name of an empty database'),
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'placeholder'    => t('database_name'),
	                    'u-prop'         => 'db.database',
                        'required'       => true,
                        'u-autocomplete' => '',
                    ],
                ],
                [
                    'type'        => 'text',
                    'name'        => 'db[username]',
                    'label'       => t('MySQL username'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => t('A user with full privileges on this database'),
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'placeholder'    => t('user_name'),
	                    'u-prop'         => 'db.username',
                        'required'       => true,
                        'u-autocomplete' => '',
                    ],
                ],
                [
                'type'        => 'text',
                    'name'        => 'db[password]',
                    'label'       => t('MySQL password'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => t('Password for the specified user'),
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'placeholder'    => t('Password'),
	                    'u-prop'         => 'db.password',
                        'required'       => true,
                        'u-autocomplete' => '',
                    ],
                ],
                [
                    'type'          => 'group',
                    'name'          => 'system',
                    'label'         => '',
                    'class'         => 'dg g-7 gtc-4 sm:gtc-1',
                    'label_class'   => '',
                    'content_class' => '',
                    'fields'        => [
                        [
                            'type'        => 'text',
                            'name'        => 'db[host]',
                            'label'       => t('Hostname'),
                            'class'       => '',
                            'label_class' => '',
                            'reset'       => 0,
                            'before'      => '',
                            'after'       => '',
                            'instruction' => '',
                            'tooltip'     => '',
                            'copy'        => 0,
                            'validator'   => '',
                            'conditions'  => [],
                            'attributes'  => [
                                'value'          => 'localhost',
                                'placeholder'    => t('Hostname'),
	                            'u-prop'         => 'db.host',
                                'required'       => true,
                                'u-autocomplete' => '',
                            ],
                        ],
                        [
                            'type'        => 'text',
                            'name'        => 'db[prefix]',
                            'label'       => t('Prefix'),
                            'class'       => '',
                            'label_class' => '',
                            'reset'       => 0,
                            'before'      => '',
                            'after'       => '',
                            'instruction' => '',
                            'tooltip'     => '',
                            'copy'        => 0,
                            'validator'   => '',
                            'conditions'  => [],
                            'attributes'  => [
                                'value'          => 'expansa_',
                                'placeholder'    => t('Prefix'),
	                            'u-prop'         => 'db.prefix',
                                'required'       => true,
                                'u-autocomplete' => '',
                            ],
                        ],
                    ],
                ],
            ],
        ],
        [
            'type'       => 'step',
            'attributes' => [
                'class'         => 'dg g-8 pt-8',
                'method'        => 'post',
                'u-step'        => 'isCompatible',
                'u-step:action' => '$ajax.post("system/test", db).then(response => ({ isCompatible, compat } = response))',
                'hidden'        => true,
            ],
            'fields'     => [
                [
                    'name'        => 'title',
                    'type'        => 'header',
                    'label'       => t('Step 2: System check'),
                    'instruction' => t('This step makes sure your server is properly configured and ready for installation.'),
                    'attributes'  => [ 'u-prop' => 'title' ],
                ],
                [
                    'name'  => 'website-data',
                    'type'  => 'divider',
                    'label' => t('System check'),
                    'attributes'  => [ 'u-prop' => 'websiteData' ],
                ],
                [
                    'name' => 'checker',
                    'type' => 'checker',
                    'attributes'  => [ 'u-prop' => 'checker' ],
                ],
            ],
        ],
        [
            'type'       => 'step',
            'attributes' => [
                'class'           => 'dg g-8 pt-8',
                'hidden'          => true,
                'u-step.required' => '',
            ],
            'fields'     => [
                [
                    'name'        => 'title',
                    'type'        => 'header',
                    'label'       => t('Step 3: Create account'),
                    'instruction' => t('Almost done! As a final step, add the website owner\'s details.'),
                    'attributes'  => [ 'u-prop' => 'title' ],
                ],
                [
                    'name'  => 'user-credits',
                    'type'  => 'divider',
                    'label' => t('Owner credentials'),
                    'attributes'  => [ 'u-prop' => 'userCredits' ],
                ],
                [
                    'type'        => 'hidden',
                    'name'        => 'user[is_verified]',
                    'label'       => '',
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => '',
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'u-prop' => 'user.isVerified',
                        'value' => true,
                    ],
                ],
                [
                    'type'        => 'email',
                    'name'        => 'user[email]',
                    'label'       => t('Your email address'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => t('Double-check your email address before continuing'),
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'placeholder'    => t('Enter email'),
                        '@change'        => "user.login = user.email.split('@')[0]",
	                    'u-prop'         => 'user.email',
	                    'required'       => true,
                        'u-autocomplete' => '',
                    ],
                ],
                [
                    'type'        => 'select',
                    'name'        => 'user[locale]',
                    'label'       => t('Your language'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => t('Set the language of your dashboard'),
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'u-prop'   => 'user.locale',
                        'u-select' => '{"showSearch": 1}',
                        'required' => true,
                    ],
                    'options'     => Expansa\Facades\I18n::languageOptions(),
                ],
                [
                    'type'        => 'text',
                    'name'        => 'user[login]',
                    'label'       => t('Your login'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => t('Only letters, numbers, underscores, hyphens, and the @ symbol are allowed'),
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'placeholder'    => t('Enter login'),
	                    'u-prop'         => 'user.login',
                        'required'       => true,
                        'u-autocomplete' => '',
                    ],
                ],
                [
                    'type'        => 'password',
                    'name'        => 'user[password]',
                    'label'       => t('Your password'),
                    'class'       => '',
                    'label_class' => '',
                    'reset'       => 0,
                    'before'      => '',
                    'after'       => '',
                    'instruction' => '',
                    'tooltip'     => '',
                    'copy'        => 0,
                    'validator'   => '',
                    'conditions'  => [],
                    'attributes'  => [
                        'placeholder'    => t('Password'),
	                    'u-prop'         => 'user.password',
                        'required'       => true,
                        'u-autocomplete' => '',
                    ],
                    // password
                    'switcher'    => 1,
                    'generator'   => 1,
                    'indicator'   => 0,
                    'characters'  => [
                        'lowercase' => 2,
                        'uppercase' => 2,
                        'special'   => 2,
                        'length'    => 12,
                        'digit'     => 2,
                    ],
                ],
            ],
        ],
        [
            'type'       => 'step',
            'attributes' => [
                'class'  => 'dg g-8 pt-8',
                'hidden' => true,
                'u-step' => '',
            ],
            'fields'     => [
                [
                    'type'     => 'custom',
                    'callback' => view('global/state', [
                        'icon'        => 'success',
                        'title'       => t('Woo-hoo, Expansa has been successfully installed!'),
                        'description' => t('We hope the installation process was easy. Thank you, and enjoy.'),
                    ])->render()
                ],
            ],
        ],
        [
            'type'     => 'custom',
            'callback' => function () {
                ?>
                <div class="py-8 df jcsb g-2">
                    <button type="button" class="btn btn--outline" u-show="isNotLast()" :disabled="cannotGoBack()" @click="goBack()" disabled>
                        <?php echo t('Back'); ?>
                    </button>
                    <button type="button" class="btn btn--primary" u-show="isSteps([1, 3])" :disabled="cannotGoNext()" @click="goNext()" disabled>
                        <?php echo t('Continue'); ?>
                    </button>
                    <button type="submit" class="btn btn--primary" u-show="isStep(4)" :disabled="cannotGoNext()" hidden disabled>
                        <?php echo t('Install Expansa'); ?>
                    </button>
                    <a href="<?php echo url('/dashboard/profile'); ?>" class="btn btn--primary mx-auto" u-show="isLast()" hidden><?php echo t('Go to dashboard'); ?></a>
                </div>
                <?php
            },
        ],
    ]
);
