<?php
/**
 * Sign In form
 *
 * @since 2025.1
 */
return \Expansa\Facades\Form::enqueue(
	'user-sign-in',
	[
		'class'           => 'dg g-6',
		'@submit.prevent' => '$ajax.post("user/sign-in")',
	],
	[
		[
			'type'        => 'header',
			'label'       => t( 'Welcome to Expansa' ),
			'name'        => 'title',
			'class'       => '',
			'instruction' => t( 'Sign in to access your dashboard and site settings.' ),
			'attributes'  => [ 'u-prop' => 'title' ],
		],
		[
			'type'        => 'text',
			'name'        => 'login',
			'label'       => t( 'Login or email' ),
			'class'       => 'field field--lg',
			'label_class' => '',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => '',
			'tooltip'     => '',
			'copy'        => 0,
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'placeholder' => t( 'Enter login or email' ),
                'u-prop'      => 'login',
                'required'    => 1,
			],
		],
		[
			'type'        => 'password',
			'name'        => 'password',
			'label'       => t('Password'),
			'class'       => 'field field--lg',
			'label_class' => '',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => t('Forgot your password? You can [reset it here](:resetPasswordLink)', url('/reset-password')),
			'tooltip'     => '',
			'copy'        => 0,
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'placeholder' => t( 'Password' ),
                'u-prop.up'   => 'password',
				'required'    => 1,
			],
			'switcher'    => 1,
			'generator'   => 0,
			'indicator'   => 0,
			'characters'  => [],
		],
		[
			'type'        => 'checkbox',
			'name'        => 'remember',
			'label'       => t( 'Remember me on this device' ),
			'class'       => '',
			'label_class' => '',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => '',
			'tooltip'     => '',
			'copy'        => 0,
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'u-prop' => 'remember',
				'checked' => true,
			],
			'options' => [],
		],
		[
			'type'        => 'submit',
			'name'        => 'sign-in',
			'label'      => t( 'Sign In' ),
			'class'       => '',
			'label_class' => '',
			'reset'       => 0,
			'before'      => '',
			'after'       => '',
			'instruction' => '',
			'tooltip'     => '',
			'copy'        => 0,
			'validator'   => '',
			'conditions'  => [],
			'attributes'  => [
				'class'     => 'btn btn--lg btn--primary btn--full',
				'disabled'  => true,
				':disabled' => '!login.trim() || !password.trim()',
			],
		],
	]
);