<?php

declare(strict_types=1);

namespace App\Support;

/**
 * Countries with their ISO codes, region and currency.
 *
 * @package App\Support
 */
final class Countries
{
    /**
     * Data of the list, kept in a constant: opcache holds it in shared memory.
     */
    private const array COUNTRIES = [
        [
            'name'     => 'Afghanistan — افغانستان',
            'iso2'     => 'AF',
            'iso3'     => 'AFG',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'AFN',
                'name'   => 'Afghan afghani',
                'native' => 'افغانی افغانستان',
                'symbol' => '؋',
            ],
        ],
        [
            'name'     => 'Åland Islands — Åland',
            'iso2'     => 'AX',
            'iso3'     => 'ALA',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Albania — Shqipëria',
            'iso2'     => 'AL',
            'iso3'     => 'ALB',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'ALL',
                'name'   => 'Albanian lek',
                'native' => 'Leku shqiptar',
                'symbol' => 'Lek',
            ],
        ],
        [
            'name'     => 'Algeria — الجزائر',
            'iso2'     => 'DZ',
            'iso3'     => 'DZA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'DZD',
                'name'   => 'Algerian dinar',
                'native' => 'دينار جزائري',
                'symbol' => 'دج',
            ],
        ],
        [
            'name'     => 'American Samoa — American Samoa',
            'iso2'     => 'AS',
            'iso3'     => 'ASM',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'US Dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Andorra — Andorra',
            'iso2'     => 'AD',
            'iso3'     => 'AND',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Angola — Angola',
            'iso2'     => 'AO',
            'iso3'     => 'AGO',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'AOA',
                'name'   => 'Angolan kwanza',
                'native' => 'Kwanza angolano',
                'symbol' => 'Kz',
            ],
        ],
        [
            'name'     => 'Anguilla — Anguilla',
            'iso2'     => 'AI',
            'iso3'     => 'AIA',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'East Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Antarctica — Antarctica',
            'iso2'     => 'AQ',
            'iso3'     => 'ATA',
            'region'   => 'AN',
            'currency' => [
                'code'   => '',
                'name'   => '',
                'native' => '',
                'symbol' => '',
            ],
        ],
        [
            'name'     => 'Antigua and Barbuda — Antigua and Barbuda',
            'iso2'     => 'AG',
            'iso3'     => 'ATG',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'Eastern Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Argentina — Argentina',
            'iso2'     => 'AR',
            'iso3'     => 'ARG',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'ARS',
                'name'   => 'Argentine peso',
                'native' => 'Peso argentino',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Armenia — Հայաստան',
            'iso2'     => 'AM',
            'iso3'     => 'ARM',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'AMD',
                'name'   => 'Armenian dram',
                'native' => 'Հայկական դրամ',
                'symbol' => '֏',
            ],
        ],
        [
            'name'     => 'Aruba — Aruba',
            'iso2'     => 'AW',
            'iso3'     => 'ABW',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'AWG',
                'name'   => 'Aruban florin',
                'native' => 'Arubaanse gulden',
                'symbol' => 'ƒ',
            ],
        ],
        [
            'name'     => 'Australia — Australia',
            'iso2'     => 'AU',
            'iso3'     => 'AUS',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Austria — Österreich',
            'iso2'     => 'AT',
            'iso3'     => 'AUT',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Azerbaijan — Azərbaycan',
            'iso2'     => 'AZ',
            'iso3'     => 'AZE',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'AZN',
                'name'   => 'Azerbaijani manat',
                'native' => 'Azərbaycan Manatı',
                'symbol' => 'm',
            ],
        ],
        [
            'name'     => 'Bahamas — Bahamas',
            'iso2'     => 'BS',
            'iso3'     => 'BHS',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'BSD',
                'name'   => 'Bahamian dollar',
                'native' => 'Bahamian Dollar',
                'symbol' => 'B$',
            ],
        ],
        [
            'name'     => 'Bahrain — البحرين',
            'iso2'     => 'BH',
            'iso3'     => 'BHR',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'BHD',
                'name'   => 'Bahraini dinar',
                'native' => 'دينار بحريني',
                'symbol' => '.د.ب',
            ],
        ],
        [
            'name'     => 'Bangladesh — বাংলাদেশ',
            'iso2'     => 'BD',
            'iso3'     => 'BGD',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'BDT',
                'name'   => 'Bangladeshi taka',
                'native' => 'বাংলাদেশী টাকা',
                'symbol' => '৳',
            ],
        ],
        [
            'name'     => 'Barbados — Barbados',
            'iso2'     => 'BB',
            'iso3'     => 'BRB',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'BBD',
                'name'   => 'Barbadian dollar',
                'native' => 'Barbadian Dollar',
                'symbol' => 'Bds$',
            ],
        ],
        [
            'name'     => 'Belarus — Беларусь',
            'iso2'     => 'BY',
            'iso3'     => 'BLR',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'BYN',
                'name'   => 'Belarusian ruble',
                'native' => 'Беларускі рубель',
                'symbol' => 'Br',
            ],
        ],
        [
            'name'     => 'Belgium — België',
            'iso2'     => 'BE',
            'iso3'     => 'BEL',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Belize — Belize',
            'iso2'     => 'BZ',
            'iso3'     => 'BLZ',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'BZD',
                'name'   => 'Belize dollar',
                'native' => 'Belize Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Benin — Bénin',
            'iso2'     => 'BJ',
            'iso3'     => 'BEN',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franc CFA (BCEAO)',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Bermuda — Bermuda',
            'iso2'     => 'BM',
            'iso3'     => 'BMU',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'BMD',
                'name'   => 'Bermudian dollar',
                'native' => 'Bermudian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Bhutan — འབྲུག་ཡུལ་',
            'iso2'     => 'BT',
            'iso3'     => 'BTN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'BTN',
                'name'   => 'Bhutanese ngultrum',
                'native' => 'དངུལ་ཀྲམ',
                'symbol' => 'Nu.',
            ],
        ],
        [
            'name'     => 'Bolivia — Bolivia',
            'iso2'     => 'BO',
            'iso3'     => 'BOL',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'BOB',
                'name'   => 'Bolivian boliviano',
                'native' => 'Boliviano',
                'symbol' => 'Bs.',
            ],
        ],
        [
            'name'     => 'Bonaire, Sint Eustatius and Saba — Caribisch Nederland',
            'iso2'     => 'BQ',
            'iso3'     => 'BES',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'Amerikaanse dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Bosnia and Herzegovina — Bosna i Hercegovina',
            'iso2'     => 'BA',
            'iso3'     => 'BIH',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'BAM',
                'name'   => 'Bosnia and Herzegovina convertible mark',
                'native' => 'Bosanskohercegovačka konvertibilna marka',
                'symbol' => 'KM',
            ],
        ],
        [
            'name'     => 'Botswana — Botswana',
            'iso2'     => 'BW',
            'iso3'     => 'BWA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'BWP',
                'name'   => 'Botswana pula',
                'native' => 'Botswana pula',
                'symbol' => 'P',
            ],
        ],
        [
            'name'     => 'Bouvet Island — Bouvetøya',
            'iso2'     => 'BV',
            'iso3'     => 'BVT',
            'region'   => 'AN',
            'currency' => [
                'code'   => 'NOK',
                'name'   => 'Norwegian Krone',
                'native' => 'Norwegian Krone',
                'symbol' => 'kr',
            ],
        ],
        [
            'name'     => 'Brazil — Brasil',
            'iso2'     => 'BR',
            'iso3'     => 'BRA',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'BRL',
                'name'   => 'Brazilian real',
                'native' => 'Real brasileiro',
                'symbol' => 'R$',
            ],
        ],
        [
            'name'     => 'British Indian Ocean Territory — British Indian Ocean Territory',
            'iso2'     => 'IO',
            'iso3'     => 'IOT',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'British Virgin Islands — British Virgin Islands',
            'iso2'     => 'VG',
            'iso3'     => 'VGB',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Brunei — Negara Brunei Darussalam',
            'iso2'     => 'BN',
            'iso3'     => 'BRN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'BND',
                'name'   => 'Brunei dollar',
                'native' => 'Dolar Brunei',
                'symbol' => 'B$',
            ],
        ],
        [
            'name'     => 'Bulgaria — България',
            'iso2'     => 'BG',
            'iso3'     => 'BGR',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'BGN',
                'name'   => 'Bulgarian lev',
                'native' => 'Български лев',
                'symbol' => 'Лв.',
            ],
        ],
        [
            'name'     => 'Burkina Faso — Burkina Faso',
            'iso2'     => 'BF',
            'iso3'     => 'BFA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franc CFA (BCEAO)',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Burundi — Burundi',
            'iso2'     => 'BI',
            'iso3'     => 'BDI',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'BIF',
                'name'   => 'Burundian franc',
                'native' => 'Franc burundais',
                'symbol' => 'FBu',
            ],
        ],
        [
            'name'     => 'Cambodia — កម្ពុជា',
            'iso2'     => 'KH',
            'iso3'     => 'KHM',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'KHR',
                'name'   => 'Cambodian riel',
                'native' => 'រៀល​កម្ពុជា',
                'symbol' => 'KHR',
            ],
        ],
        [
            'name'     => 'Cameroon — Cameroun',
            'iso2'     => 'CM',
            'iso3'     => 'CMR',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XAF',
                'name'   => 'Central African CFA franc',
                'native' => 'Franc CFA (BEAC)',
                'symbol' => 'FCFA',
            ],
        ],
        [
            'name'     => 'Canada — Canada',
            'iso2'     => 'CA',
            'iso3'     => 'CAN',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'CAD',
                'name'   => 'Canadian dollar',
                'native' => 'Canadian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Cape Verde — Cabo Verde',
            'iso2'     => 'CV',
            'iso3'     => 'CPV',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'CVE',
                'name'   => 'Cape Verdean escudo',
                'native' => 'Escudo cabo-verdiano',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Cayman Islands — Cayman Islands',
            'iso2'     => 'KY',
            'iso3'     => 'CYM',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'KYD',
                'name'   => 'Cayman Islands dollar',
                'native' => 'Cayman Islands Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Central African Republic — Ködörösêse tî Bêafrîka',
            'iso2'     => 'CF',
            'iso3'     => 'CAF',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XAF',
                'name'   => 'Central African CFA franc',
                'native' => 'Franc CFA (BEAC)',
                'symbol' => 'FCFA',
            ],
        ],
        [
            'name'     => 'Chad — Tchad',
            'iso2'     => 'TD',
            'iso3'     => 'TCD',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XAF',
                'name'   => 'Central African CFA franc',
                'native' => 'Franc CFA (BEAC)',
                'symbol' => 'FCFA',
            ],
        ],
        [
            'name'     => 'Chile — Chile',
            'iso2'     => 'CL',
            'iso3'     => 'CHL',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'CLP',
                'name'   => 'Chilean peso',
                'native' => 'Peso chileno',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'China — 中国',
            'iso2'     => 'CN',
            'iso3'     => 'CHN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'CNY',
                'name'   => 'Chinese yuan',
                'native' => '人民币',
                'symbol' => '¥',
            ],
        ],
        [
            'name'     => 'Christmas Island — Christmas Island',
            'iso2'     => 'CX',
            'iso3'     => 'CXR',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Cocos (Keeling) Islands — Cocos (Keeling) Islands',
            'iso2'     => 'CC',
            'iso3'     => 'CCK',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Colombia — Colombia',
            'iso2'     => 'CO',
            'iso3'     => 'COL',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'COP',
                'name'   => 'Colombian peso',
                'native' => 'Peso colombiano',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Comoros — Komori',
            'iso2'     => 'KM',
            'iso3'     => 'COM',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'KMF',
                'name'   => 'Comorian franc',
                'native' => 'Franc comorien',
                'symbol' => 'CF',
            ],
        ],
        [
            'name'     => 'Congo — République du Congo',
            'iso2'     => 'CG',
            'iso3'     => 'COG',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XAF',
                'name'   => 'Central African CFA franc',
                'native' => 'Franc CFA (BEAC)',
                'symbol' => 'FC',
            ],
        ],
        [
            'name'     => 'Cook Islands — Cook Islands',
            'iso2'     => 'CK',
            'iso3'     => 'COK',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'NZD',
                'name'   => 'Cook Islands dollar',
                'native' => 'New Zealand Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Costa Rica — Costa Rica',
            'iso2'     => 'CR',
            'iso3'     => 'CRI',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'CRC',
                'name'   => 'Costa Rican colón',
                'native' => 'Colón costarricense',
                'symbol' => '₡',
            ],
        ],
        [
            'name'     => 'Côte d’Ivoire — Côte d’Ivoire',
            'iso2'     => 'CI',
            'iso3'     => 'CIV',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franc CFA (BCEAO)',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Croatia — Hrvatska',
            'iso2'     => 'HR',
            'iso3'     => 'HRV',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Cuba — Cuba',
            'iso2'     => 'CU',
            'iso3'     => 'CUB',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'CUP',
                'name'   => 'Cuban peso',
                'native' => 'Peso cubano',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Curaçao — Curaçao',
            'iso2'     => 'CW',
            'iso3'     => 'CUW',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCG',
                'name'   => 'Caribbean guilder',
                'native' => 'Caribische gulden',
                'symbol' => 'Cg',
            ],
        ],
        [
            'name'     => 'Cyprus — Κύπρος',
            'iso2'     => 'CY',
            'iso3'     => 'CYP',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Ευρώ',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Czechia — Česko',
            'iso2'     => 'CZ',
            'iso3'     => 'CZE',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'CZK',
                'name'   => 'Czech koruna',
                'native' => 'Česká koruna',
                'symbol' => 'Kč',
            ],
        ],
        [
            'name'     => 'Democratic Republic of the Congo — République démocratique du Congo',
            'iso2'     => 'CD',
            'iso3'     => 'COD',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'CDF',
                'name'   => 'Congolese Franc',
                'native' => 'Franc congolais',
                'symbol' => 'FC',
            ],
        ],
        [
            'name'     => 'Denmark — Danmark',
            'iso2'     => 'DK',
            'iso3'     => 'DNK',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'DKK',
                'name'   => 'Danish krone',
                'native' => 'Dansk krone',
                'symbol' => 'Kr.',
            ],
        ],
        [
            'name'     => 'Djibouti — Djibouti',
            'iso2'     => 'DJ',
            'iso3'     => 'DJI',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'DJF',
                'name'   => 'Djiboutian franc',
                'native' => 'Franc djiboutien',
                'symbol' => 'Fdj',
            ],
        ],
        [
            'name'     => 'Dominica — Dominica',
            'iso2'     => 'DM',
            'iso3'     => 'DMA',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'Eastern Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Dominican Republic — República Dominicana',
            'iso2'     => 'DO',
            'iso3'     => 'DOM',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'DOP',
                'name'   => 'Dominican peso',
                'native' => 'Peso dominicano',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Ecuador — Ecuador',
            'iso2'     => 'EC',
            'iso3'     => 'ECU',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'Dólar estadounidense',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Egypt — مصر',
            'iso2'     => 'EG',
            'iso3'     => 'EGY',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'EGP',
                'name'   => 'Egyptian pound',
                'native' => 'جنيه مصري',
                'symbol' => 'ج.م',
            ],
        ],
        [
            'name'     => 'El Salvador — El Salvador',
            'iso2'     => 'SV',
            'iso3'     => 'SLV',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'Dólar estadounidense',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Equatorial Guinea — Guinea Ecuatorial',
            'iso2'     => 'GQ',
            'iso3'     => 'GNQ',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XAF',
                'name'   => 'Central African CFA franc',
                'native' => 'Franco CFA de África Central',
                'symbol' => 'FCFA',
            ],
        ],
        [
            'name'     => 'Eritrea — ኤርትራ',
            'iso2'     => 'ER',
            'iso3'     => 'ERI',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'ERN',
                'name'   => 'Eritrean nakfa',
                'native' => 'ናቕፋ',
                'symbol' => 'Nfk',
            ],
        ],
        [
            'name'     => 'Estonia — Eesti',
            'iso2'     => 'EE',
            'iso3'     => 'EST',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Eswatini — eSwatini',
            'iso2'     => 'SZ',
            'iso3'     => 'SWZ',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'SZL',
                'name'   => 'Lilangeni',
                'native' => 'Lilangeni',
                'symbol' => 'E',
            ],
        ],
        [
            'name'     => 'Ethiopia — ኢትዮጵያ',
            'iso2'     => 'ET',
            'iso3'     => 'ETH',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'ETB',
                'name'   => 'Ethiopian birr',
                'native' => 'የኢትዮጵያ ብር',
                'symbol' => 'Nkf',
            ],
        ],
        [
            'name'     => 'Falkland Islands — Falkland Islands',
            'iso2'     => 'FK',
            'iso3'     => 'FLK',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'FKP',
                'name'   => 'Falkland Islands pound',
                'native' => 'Falkland Islands Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Faroe Islands — Føroyar',
            'iso2'     => 'FO',
            'iso3'     => 'FRO',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'DKK',
                'name'   => 'Danish krone',
                'native' => 'Donsk króna',
                'symbol' => 'Kr.',
            ],
        ],
        [
            'name'     => 'Fiji — Fiji',
            'iso2'     => 'FJ',
            'iso3'     => 'FJI',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'FJD',
                'name'   => 'Fijian dollar',
                'native' => 'Fijian Dollar',
                'symbol' => 'FJ$',
            ],
        ],
        [
            'name'     => 'Finland — Suomi',
            'iso2'     => 'FI',
            'iso3'     => 'FIN',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'France — France',
            'iso2'     => 'FR',
            'iso3'     => 'FRA',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'French Guiana — Guyane française',
            'iso2'     => 'GF',
            'iso3'     => 'GUF',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'French Polynesia — Polynésie française',
            'iso2'     => 'PF',
            'iso3'     => 'PYF',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'XPF',
                'name'   => 'CFP franc',
                'native' => 'Franc CFP',
                'symbol' => '₣',
            ],
        ],
        [
            'name'     => 'French Southern Territories — Terres australes et antarctiques françaises',
            'iso2'     => 'TF',
            'iso3'     => 'ATF',
            'region'   => 'AN',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Gabon — Gabon',
            'iso2'     => 'GA',
            'iso3'     => 'GAB',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XAF',
                'name'   => 'Central African CFA franc',
                'native' => 'Franc CFA (BEAC)',
                'symbol' => 'FCFA',
            ],
        ],
        [
            'name'     => 'Gambia — Gambia',
            'iso2'     => 'GM',
            'iso3'     => 'GMB',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'GMD',
                'name'   => 'Gambian dalasi',
                'native' => 'Gambian Dalasi',
                'symbol' => 'D',
            ],
        ],
        [
            'name'     => 'Georgia — საქართველო',
            'iso2'     => 'GE',
            'iso3'     => 'GEO',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'GEL',
                'name'   => 'Georgian lari',
                'native' => 'Ქართული ლარი',
                'symbol' => 'ლ',
            ],
        ],
        [
            'name'     => 'Germany — Deutschland',
            'iso2'     => 'DE',
            'iso3'     => 'DEU',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Ghana — Ghana',
            'iso2'     => 'GH',
            'iso3'     => 'GHA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'GHS',
                'name'   => 'Ghanaian cedi',
                'native' => 'Ghanaian Cedi',
                'symbol' => 'GH₵',
            ],
        ],
        [
            'name'     => 'Gibraltar — Gibraltar',
            'iso2'     => 'GI',
            'iso3'     => 'GIB',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'GIP',
                'name'   => 'Gibraltar pound',
                'native' => 'Gibraltar Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Greece — Ελλάδα',
            'iso2'     => 'GR',
            'iso3'     => 'GRC',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Ευρώ',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Greenland — Kalaallit Nunaat',
            'iso2'     => 'GL',
            'iso3'     => 'GRL',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'DKK',
                'name'   => 'Danish krone',
                'native' => 'Danish krone',
                'symbol' => 'Kr.',
            ],
        ],
        [
            'name'     => 'Grenada — Grenada',
            'iso2'     => 'GD',
            'iso3'     => 'GRD',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'Eastern Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Guadeloupe — Guadeloupe',
            'iso2'     => 'GP',
            'iso3'     => 'GLP',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Guam — Guam',
            'iso2'     => 'GU',
            'iso3'     => 'GUM',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'US Dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Guatemala — Guatemala',
            'iso2'     => 'GT',
            'iso3'     => 'GTM',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'GTQ',
                'name'   => 'Guatemalan quetzal',
                'native' => 'Quetzal',
                'symbol' => 'Q',
            ],
        ],
        [
            'name'     => 'Guernsey — Guernsey',
            'iso2'     => 'GG',
            'iso3'     => 'GGY',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'GBP',
                'name'   => 'British pound',
                'native' => 'UK Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Guinea — Guinée',
            'iso2'     => 'GN',
            'iso3'     => 'GIN',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'GNF',
                'name'   => 'Guinean franc',
                'native' => 'Franc guinéen',
                'symbol' => 'FG',
            ],
        ],
        [
            'name'     => 'Guinea-Bissau — Guiné-Bissau',
            'iso2'     => 'GW',
            'iso3'     => 'GNB',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franco CFA de BCEAO',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Guyana — Guyana',
            'iso2'     => 'GY',
            'iso3'     => 'GUY',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'GYD',
                'name'   => 'Guyanese dollar',
                'native' => 'Guyanaese Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Haiti — Haïti',
            'iso2'     => 'HT',
            'iso3'     => 'HTI',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'HTG',
                'name'   => 'Haitian gourde',
                'native' => 'Gourde haïtienne',
                'symbol' => 'G',
            ],
        ],
        [
            'name'     => 'Heard Island and McDonald Islands — Heard Island and McDonald Islands',
            'iso2'     => 'HM',
            'iso3'     => 'HMD',
            'region'   => 'AN',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Honduras — Honduras',
            'iso2'     => 'HN',
            'iso3'     => 'HND',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'HNL',
                'name'   => 'Honduran lempira',
                'native' => 'Lempira hondureño',
                'symbol' => 'L',
            ],
        ],
        [
            'name'     => 'Hong Kong — 香港',
            'iso2'     => 'HK',
            'iso3'     => 'HKG',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'HKD',
                'name'   => 'Hong Kong dollar',
                'native' => '港元',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Hungary — Magyarország',
            'iso2'     => 'HU',
            'iso3'     => 'HUN',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'HUF',
                'name'   => 'Hungarian forint',
                'native' => 'Magyar forint',
                'symbol' => 'Ft',
            ],
        ],
        [
            'name'     => 'Iceland — Ísland',
            'iso2'     => 'IS',
            'iso3'     => 'ISL',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'ISK',
                'name'   => 'Icelandic króna',
                'native' => 'Íslensk króna',
                'symbol' => 'kr',
            ],
        ],
        [
            'name'     => 'India — भारत',
            'iso2'     => 'IN',
            'iso3'     => 'IND',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'INR',
                'name'   => 'Indian rupee',
                'native' => 'भारतीय रुपया',
                'symbol' => '₹',
            ],
        ],
        [
            'name'     => 'Indonesia — Indonesia',
            'iso2'     => 'ID',
            'iso3'     => 'IDN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'IDR',
                'name'   => 'Indonesian rupiah',
                'native' => 'Rupiah Indonesia',
                'symbol' => 'Rp',
            ],
        ],
        [
            'name'     => 'Iran — ایران',
            'iso2'     => 'IR',
            'iso3'     => 'IRN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'IRR',
                'name'   => 'Iranian rial',
                'native' => 'ریال ایران',
                'symbol' => '﷼',
            ],
        ],
        [
            'name'     => 'Iraq — العراق',
            'iso2'     => 'IQ',
            'iso3'     => 'IRQ',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'IQD',
                'name'   => 'Iraqi dinar',
                'native' => 'دينار عراقي',
                'symbol' => 'د.ع',
            ],
        ],
        [
            'name'     => 'Ireland — Éire',
            'iso2'     => 'IE',
            'iso3'     => 'IRL',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Isle of Man — Isle of Man',
            'iso2'     => 'IM',
            'iso3'     => 'IMN',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'GBP',
                'name'   => 'British pound',
                'native' => 'UK Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Israel — ישראל',
            'iso2'     => 'IL',
            'iso3'     => 'ISR',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'ILS',
                'name'   => 'Israeli new shekel',
                'native' => 'שקל חדש',
                'symbol' => '₪',
            ],
        ],
        [
            'name'     => 'Italy — Italia',
            'iso2'     => 'IT',
            'iso3'     => 'ITA',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Jamaica — Jamaica',
            'iso2'     => 'JM',
            'iso3'     => 'JAM',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'JMD',
                'name'   => 'Jamaican dollar',
                'native' => 'Jamaican Dollar',
                'symbol' => 'J$',
            ],
        ],
        [
            'name'     => 'Japan — 日本',
            'iso2'     => 'JP',
            'iso3'     => 'JPN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'JPY',
                'name'   => 'Japanese yen',
                'native' => '日本円',
                'symbol' => '¥',
            ],
        ],
        [
            'name'     => 'Jersey — Jersey',
            'iso2'     => 'JE',
            'iso3'     => 'JEY',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'GBP',
                'name'   => 'British pound',
                'native' => 'UK Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Jordan — الأردن',
            'iso2'     => 'JO',
            'iso3'     => 'JOR',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'JOD',
                'name'   => 'Jordanian dinar',
                'native' => 'دينار أردني',
                'symbol' => 'ا.د',
            ],
        ],
        [
            'name'     => 'Kazakhstan — Қазақстан',
            'iso2'     => 'KZ',
            'iso3'     => 'KAZ',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'KZT',
                'name'   => 'Kazakhstani tenge',
                'native' => 'Қазақстан теңгесі',
                'symbol' => 'лв',
            ],
        ],
        [
            'name'     => 'Kenya — Kenya',
            'iso2'     => 'KE',
            'iso3'     => 'KEN',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'KES',
                'name'   => 'Kenyan shilling',
                'native' => 'Shilingi ya Kenya',
                'symbol' => 'KSh',
            ],
        ],
        [
            'name'     => 'Kiribati — Kiribati',
            'iso2'     => 'KI',
            'iso3'     => 'KIR',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Kosovo — Republika e Kosovës',
            'iso2'     => 'XK',
            'iso3'     => 'XKX',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euroja',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Kuwait — الكويت',
            'iso2'     => 'KW',
            'iso3'     => 'KWT',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'KWD',
                'name'   => 'Kuwaiti dinar',
                'native' => 'دينار كويتي',
                'symbol' => 'ك.د',
            ],
        ],
        [
            'name'     => 'Kyrgyzstan — Кыргызстан',
            'iso2'     => 'KG',
            'iso3'     => 'KGZ',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'KGS',
                'name'   => 'Kyrgyzstani som',
                'native' => 'Кыргызстан сому',
                'symbol' => 'лв',
            ],
        ],
        [
            'name'     => 'Laos — ສປປລາວ',
            'iso2'     => 'LA',
            'iso3'     => 'LAO',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'LAK',
                'name'   => 'Lao kip',
                'native' => 'ລາວ ກີບ',
                'symbol' => '₭',
            ],
        ],
        [
            'name'     => 'Latvia — Latvija',
            'iso2'     => 'LV',
            'iso3'     => 'LVA',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Eiro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Lebanon — لبنان',
            'iso2'     => 'LB',
            'iso3'     => 'LBN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'LBP',
                'name'   => 'Lebanese pound',
                'native' => 'جنيه لبناني',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Lesotho — Lesotho',
            'iso2'     => 'LS',
            'iso3'     => 'LSO',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'LSL',
                'name'   => 'Lesotho loti',
                'native' => 'Lesotho loti',
                'symbol' => 'L',
            ],
        ],
        [
            'name'     => 'Liberia — Liberia',
            'iso2'     => 'LR',
            'iso3'     => 'LBR',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'LRD',
                'name'   => 'Liberian dollar',
                'native' => 'Liberian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Libya — ليبيا',
            'iso2'     => 'LY',
            'iso3'     => 'LBY',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'LYD',
                'name'   => 'Libyan dinar',
                'native' => 'دينار ليبي',
                'symbol' => 'د.ل',
            ],
        ],
        [
            'name'     => 'Liechtenstein — Liechtenstein',
            'iso2'     => 'LI',
            'iso3'     => 'LIE',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'CHF',
                'name'   => 'Swiss franc',
                'native' => 'Schweizer Franken',
                'symbol' => 'CHf',
            ],
        ],
        [
            'name'     => 'Lithuania — Lietuva',
            'iso2'     => 'LT',
            'iso3'     => 'LTU',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euras',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Luxembourg — Luxembourg',
            'iso2'     => 'LU',
            'iso3'     => 'LUX',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Macao — 澳門',
            'iso2'     => 'MO',
            'iso3'     => 'MAC',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'MOP',
                'name'   => 'Macanese pataca',
                'native' => '澳門元',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Madagascar — Madagasikara',
            'iso2'     => 'MG',
            'iso3'     => 'MDG',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'MGA',
                'name'   => 'Malagasy ariary',
                'native' => 'Ariary',
                'symbol' => 'Ar',
            ],
        ],
        [
            'name'     => 'Malawi — Malawi',
            'iso2'     => 'MW',
            'iso3'     => 'MWI',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'MWK',
                'name'   => 'Malawian kwacha',
                'native' => 'Malawian kwacha',
                'symbol' => 'MK',
            ],
        ],
        [
            'name'     => 'Malaysia — Malaysia',
            'iso2'     => 'MY',
            'iso3'     => 'MYS',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'MYR',
                'name'   => 'Malaysian ringgit',
                'native' => 'Ringgit Malaysia',
                'symbol' => 'RM',
            ],
        ],
        [
            'name'     => 'Maldives — ދިވެހިރާއްޖެ',
            'iso2'     => 'MV',
            'iso3'     => 'MDV',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'MVR',
                'name'   => 'Maldivian rufiyaa',
                'native' => 'Maldivian rufiyaa',
                'symbol' => 'Rf',
            ],
        ],
        [
            'name'     => 'Mali — Mali',
            'iso2'     => 'ML',
            'iso3'     => 'MLI',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franc CFA (BCEAO)',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Malta — Malta',
            'iso2'     => 'MT',
            'iso3'     => 'MLT',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Ewro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Marshall Islands — M̧ajeļ',
            'iso2'     => 'MH',
            'iso3'     => 'MHL',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Martinique — Martinique',
            'iso2'     => 'MQ',
            'iso3'     => 'MTQ',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Mauritania — موريتانيا',
            'iso2'     => 'MR',
            'iso3'     => 'MRT',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'MRU',
                'name'   => 'Mauritanian ouguiya',
                'native' => 'أوقية موريتانية',
                'symbol' => 'UM',
            ],
        ],
        [
            'name'     => 'Mauritius — Maurice',
            'iso2'     => 'MU',
            'iso3'     => 'MUS',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'MUR',
                'name'   => 'Mauritian rupee',
                'native' => 'Mauritian Rupee',
                'symbol' => '₨',
            ],
        ],
        [
            'name'     => 'Mayotte — Mayotte',
            'iso2'     => 'YT',
            'iso3'     => 'MYT',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Mexico — México',
            'iso2'     => 'MX',
            'iso3'     => 'MEX',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'MXN',
                'name'   => 'Mexican peso',
                'native' => 'Peso mexicano',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Micronesia — Micronesia',
            'iso2'     => 'FM',
            'iso3'     => 'FSM',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Moldova — Moldova',
            'iso2'     => 'MD',
            'iso3'     => 'MDA',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'MDL',
                'name'   => 'Moldovan leu',
                'native' => 'Leu moldovenesc',
                'symbol' => 'L',
            ],
        ],
        [
            'name'     => 'Monaco — Monaco',
            'iso2'     => 'MC',
            'iso3'     => 'MCO',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Mongolia — Монгол улс',
            'iso2'     => 'MN',
            'iso3'     => 'MNG',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'MNT',
                'name'   => 'Mongolian tögrög',
                'native' => 'Монгол төгрөг',
                'symbol' => '₮',
            ],
        ],
        [
            'name'     => 'Montenegro — Црна Гора',
            'iso2'     => 'ME',
            'iso3'     => 'MNE',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Evro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Montserrat — Montserrat',
            'iso2'     => 'MS',
            'iso3'     => 'MSR',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'Eastern Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Morocco — المغرب',
            'iso2'     => 'MA',
            'iso3'     => 'MAR',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'MAD',
                'name'   => 'Moroccan dirham',
                'native' => 'درهم مغربي',
                'symbol' => 'DH',
            ],
        ],
        [
            'name'     => 'Mozambique — Moçambique',
            'iso2'     => 'MZ',
            'iso3'     => 'MOZ',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'MZN',
                'name'   => 'Mozambican metical',
                'native' => 'Metical moçambicano',
                'symbol' => 'MT',
            ],
        ],
        [
            'name'     => 'Myanmar — မြန်မာ',
            'iso2'     => 'MM',
            'iso3'     => 'MMR',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'MMK',
                'name'   => 'Burmese kyat',
                'native' => 'မြန်မာ ကျပ်',
                'symbol' => 'K',
            ],
        ],
        [
            'name'     => 'Namibia — Namibia',
            'iso2'     => 'NA',
            'iso3'     => 'NAM',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'NAD',
                'name'   => 'Namibian dollar',
                'native' => 'Namibian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Nauru — Nauru',
            'iso2'     => 'NR',
            'iso3'     => 'NRU',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Nepal — नेपाल',
            'iso2'     => 'NP',
            'iso3'     => 'NPL',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'NPR',
                'name'   => 'Nepalese rupee',
                'native' => 'नेपाली रूपैयाँ',
                'symbol' => '₨',
            ],
        ],
        [
            'name'     => 'Netherlands — Nederland',
            'iso2'     => 'NL',
            'iso3'     => 'NLD',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'New Caledonia — Nouvelle-Calédonie',
            'iso2'     => 'NC',
            'iso3'     => 'NCL',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'XPF',
                'name'   => 'CFP franc',
                'native' => 'Franc CFP',
                'symbol' => '₣',
            ],
        ],
        [
            'name'     => 'New Zealand — New Zealand',
            'iso2'     => 'NZ',
            'iso3'     => 'NZL',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'NZD',
                'name'   => 'New Zealand dollar',
                'native' => 'New Zealand Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Nicaragua — Nicaragua',
            'iso2'     => 'NI',
            'iso3'     => 'NIC',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'NIO',
                'name'   => 'Nicaraguan córdoba',
                'native' => 'Córdoba nicaragüense',
                'symbol' => 'C$',
            ],
        ],
        [
            'name'     => 'Niger — Niger',
            'iso2'     => 'NE',
            'iso3'     => 'NER',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franc CFA (BCEAO)',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Nigeria — Nigeria',
            'iso2'     => 'NG',
            'iso3'     => 'NGA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'NGN',
                'name'   => 'Nigerian naira',
                'native' => 'Nigerian Naira',
                'symbol' => '₦',
            ],
        ],
        [
            'name'     => 'Niue — Niuē',
            'iso2'     => 'NU',
            'iso3'     => 'NIU',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'NZD',
                'name'   => 'New Zealand dollar',
                'native' => 'New Zealand Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Norfolk Island — Norfolk Island',
            'iso2'     => 'NF',
            'iso3'     => 'NFK',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'North Korea — 조선',
            'iso2'     => 'KP',
            'iso3'     => 'PRK',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'KPW',
                'name'   => 'North Korean Won',
                'native' => '조선 민주주의 인민 공화국 원',
                'symbol' => '₩',
            ],
        ],
        [
            'name'     => 'North Macedonia — Северна Македонија',
            'iso2'     => 'MK',
            'iso3'     => 'MKD',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'MKD',
                'name'   => 'Denar',
                'native' => 'Македонски денар',
                'symbol' => 'ден',
            ],
        ],
        [
            'name'     => 'Northern Mariana Islands — Northern Mariana Islands',
            'iso2'     => 'MP',
            'iso3'     => 'MNP',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Norway — Norge',
            'iso2'     => 'NO',
            'iso3'     => 'NOR',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'NOK',
                'name'   => 'Norwegian krone',
                'native' => 'Norwegian krone',
                'symbol' => 'kr',
            ],
        ],
        [
            'name'     => 'Oman — عمان',
            'iso2'     => 'OM',
            'iso3'     => 'OMN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'OMR',
                'name'   => 'Omani rial',
                'native' => 'ريال عماني',
                'symbol' => '.ع.ر',
            ],
        ],
        [
            'name'     => 'Pakistan — پاکستان',
            'iso2'     => 'PK',
            'iso3'     => 'PAK',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'PKR',
                'name'   => 'Pakistani rupee',
                'native' => 'پاکستانی روپیہ',
                'symbol' => '₨',
            ],
        ],
        [
            'name'     => 'Palau — Palau',
            'iso2'     => 'PW',
            'iso3'     => 'PLW',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Palestine — فلسطين',
            'iso2'     => 'PS',
            'iso3'     => 'PSE',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'ILS',
                'name'   => 'Israeli new shekel',
                'native' => 'شيكل إسرائيلي جديد',
                'symbol' => '₪',
            ],
        ],
        [
            'name'     => 'Panama — Panamá',
            'iso2'     => 'PA',
            'iso3'     => 'PAN',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'PAB',
                'name'   => 'Panamanian balboa',
                'native' => 'Balboa panameño',
                'symbol' => 'B/.',
            ],
        ],
        [
            'name'     => 'Papua New Guinea — Papua Niugini',
            'iso2'     => 'PG',
            'iso3'     => 'PNG',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'PGK',
                'name'   => 'Papua New Guinean kina',
                'native' => 'Papua New Guinean Kina',
                'symbol' => 'K',
            ],
        ],
        [
            'name'     => 'Paraguay — Paraguay',
            'iso2'     => 'PY',
            'iso3'     => 'PRY',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'PYG',
                'name'   => 'Paraguayan guarani',
                'native' => 'Guaraní paraguayo',
                'symbol' => '₲',
            ],
        ],
        [
            'name'     => 'Peru — Perú',
            'iso2'     => 'PE',
            'iso3'     => 'PER',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'PEN',
                'name'   => 'Peruvian sol',
                'native' => 'Sol peruano',
                'symbol' => 'S/.',
            ],
        ],
        [
            'name'     => 'Philippines — Pilipinas',
            'iso2'     => 'PH',
            'iso3'     => 'PHL',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'PHP',
                'name'   => 'Philippine peso',
                'native' => 'Piso ng Pilipinas',
                'symbol' => '₱',
            ],
        ],
        [
            'name'     => 'Pitcairn Islands — Pitcairn Islands',
            'iso2'     => 'PN',
            'iso3'     => 'PCN',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'NZD',
                'name'   => 'New Zealand dollar',
                'native' => 'New Zealand Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Poland — Polska',
            'iso2'     => 'PL',
            'iso3'     => 'POL',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'PLN',
                'name'   => 'Polish złoty',
                'native' => 'Złoty polski',
                'symbol' => 'zł',
            ],
        ],
        [
            'name'     => 'Portugal — Portugal',
            'iso2'     => 'PT',
            'iso3'     => 'PRT',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Puerto Rico — Puerto Rico',
            'iso2'     => 'PR',
            'iso3'     => 'PRI',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'Dólar estadounidense',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Qatar — قطر',
            'iso2'     => 'QA',
            'iso3'     => 'QAT',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'QAR',
                'name'   => 'Qatari riyal',
                'native' => 'ريال قطري',
                'symbol' => 'ق.ر',
            ],
        ],
        [
            'name'     => 'Réunion — La Réunion',
            'iso2'     => 'RE',
            'iso3'     => 'REU',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Romania — România',
            'iso2'     => 'RO',
            'iso3'     => 'ROU',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'RON',
                'name'   => 'Romanian leu',
                'native' => 'Leu românesc',
                'symbol' => 'lei',
            ],
        ],
        [
            'name'     => 'Russia — Россия',
            'iso2'     => 'RU',
            'iso3'     => 'RUS',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'RUB',
                'name'   => 'Russian ruble',
                'native' => 'Российский рубль',
                'symbol' => '₽',
            ],
        ],
        [
            'name'     => 'Rwanda — Rwanda',
            'iso2'     => 'RW',
            'iso3'     => 'RWA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'RWF',
                'name'   => 'Rwandan franc',
                'native' => 'Rwandan franc',
                'symbol' => 'FRw',
            ],
        ],
        [
            'name'     => 'Saint Barthélemy — Saint-Barthélemy',
            'iso2'     => 'BL',
            'iso3'     => 'BLM',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Saint Helena — Saint Helena',
            'iso2'     => 'SH',
            'iso3'     => 'SHN',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'SHP',
                'name'   => 'Saint Helena pound',
                'native' => 'St Helena Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Saint Kitts and Nevis — Saint Kitts and Nevis',
            'iso2'     => 'KN',
            'iso3'     => 'KNA',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'Eastern Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Saint Lucia — Saint Lucia',
            'iso2'     => 'LC',
            'iso3'     => 'LCA',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'Eastern Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Saint Pierre and Miquelon — Saint-Pierre-et-Miquelon',
            'iso2'     => 'PM',
            'iso3'     => 'SPM',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Saint Vincent and the Grenadines — Saint Vincent and the Grenadines',
            'iso2'     => 'VC',
            'iso3'     => 'VCT',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCD',
                'name'   => 'Eastern Caribbean dollar',
                'native' => 'East Caribbean Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Saint-Martin (French part) — Saint-Martin',
            'iso2'     => 'MF',
            'iso3'     => 'MAF',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Samoa — Samoa',
            'iso2'     => 'WS',
            'iso3'     => 'WSM',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'WST',
                'name'   => 'Samoan tālā',
                'native' => 'Samoan tālā',
                'symbol' => 'SAT',
            ],
        ],
        [
            'name'     => 'San Marino — San Marino',
            'iso2'     => 'SM',
            'iso3'     => 'SMR',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'São Tomé and Príncipe — São Tomé e Príncipe',
            'iso2'     => 'ST',
            'iso3'     => 'STP',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'STN',
                'name'   => 'São Tomé and Príncipe dobra',
                'native' => 'Dobra de São Tomé e Príncipe',
                'symbol' => 'Db',
            ],
        ],
        [
            'name'     => 'Saudi Arabia — المملكة العربية السعودية',
            'iso2'     => 'SA',
            'iso3'     => 'SAU',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'SAR',
                'name'   => 'Saudi riyal',
                'native' => 'ريال سعودي',
                'symbol' => '﷼',
            ],
        ],
        [
            'name'     => 'Senegal — Sénégal',
            'iso2'     => 'SN',
            'iso3'     => 'SEN',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franc CFA (BCEAO)',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Serbia — Србија',
            'iso2'     => 'RS',
            'iso3'     => 'SRB',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'RSD',
                'name'   => 'Serbian dinar',
                'native' => 'Српски динар',
                'symbol' => 'din',
            ],
        ],
        [
            'name'     => 'Seychelles — Seychelles',
            'iso2'     => 'SC',
            'iso3'     => 'SYC',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'SCR',
                'name'   => 'Seychellois rupee',
                'native' => 'Seychellois Rupee',
                'symbol' => 'SRe',
            ],
        ],
        [
            'name'     => 'Sierra Leone — Sierra Leone',
            'iso2'     => 'SL',
            'iso3'     => 'SLE',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'SLE',
                'name'   => 'Sierra Leonean leone',
                'native' => 'Sierra Leonean Leone',
                'symbol' => 'Le',
            ],
        ],
        [
            'name'     => 'Singapore — Singapore',
            'iso2'     => 'SG',
            'iso3'     => 'SGP',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'SGD',
                'name'   => 'Singapore dollar',
                'native' => 'Singapore Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Sint Maarten (Dutch part) — Sint Maarten',
            'iso2'     => 'SX',
            'iso3'     => 'SXM',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'XCG',
                'name'   => 'Caribbean guilder',
                'native' => 'Caribische gulden',
                'symbol' => 'Cg',
            ],
        ],
        [
            'name'     => 'Slovakia — Slovensko',
            'iso2'     => 'SK',
            'iso3'     => 'SVK',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Slovenia — Slovenija',
            'iso2'     => 'SI',
            'iso3'     => 'SVN',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Evro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Solomon Islands — Solomon Islands',
            'iso2'     => 'SB',
            'iso3'     => 'SLB',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'SBD',
                'name'   => 'Solomon Islands dollar',
                'native' => 'Solomon Islands Dollar',
                'symbol' => 'Si$',
            ],
        ],
        [
            'name'     => 'Somalia — Soomaaliya',
            'iso2'     => 'SO',
            'iso3'     => 'SOM',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'SOS',
                'name'   => 'Somali shilling',
                'native' => 'Shilingka Soomaaliya',
                'symbol' => 'Sh.so.',
            ],
        ],
        [
            'name'     => 'South Africa — South Africa',
            'iso2'     => 'ZA',
            'iso3'     => 'ZAF',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'ZAR',
                'name'   => 'South African rand',
                'native' => 'South African Rand',
                'symbol' => 'R',
            ],
        ],
        [
            'name'     => 'South Georgia and the South Sandwich Islands — South Georgia and the South Sandwich Islands',
            'iso2'     => 'GS',
            'iso3'     => 'SGS',
            'region'   => 'AN',
            'currency' => [
                'code'   => 'GBP',
                'name'   => 'British pound',
                'native' => 'British Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'South Korea — 대한민국',
            'iso2'     => 'KR',
            'iso3'     => 'KOR',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'KRW',
                'name'   => 'Won',
                'native' => '대한민국 원',
                'symbol' => '₩',
            ],
        ],
        [
            'name'     => 'South Sudan — South Sudan',
            'iso2'     => 'SS',
            'iso3'     => 'SSD',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'SSP',
                'name'   => 'South Sudanese pound',
                'native' => 'South Sudanese Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'Spain — España',
            'iso2'     => 'ES',
            'iso3'     => 'ESP',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Sri Lanka — ශ්‍රී ලංකාව',
            'iso2'     => 'LK',
            'iso3'     => 'LKA',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'LKR',
                'name'   => 'Sri Lankan rupee',
                'native' => 'ශ්‍රී ලංකා රුපියල',
                'symbol' => 'Rs',
            ],
        ],
        [
            'name'     => 'Sudan — السودان',
            'iso2'     => 'SD',
            'iso3'     => 'SDN',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'SDG',
                'name'   => 'Sudanese pound',
                'native' => 'جنيه سوداني',
                'symbol' => '.س.ج',
            ],
        ],
        [
            'name'     => 'Suriname — Suriname',
            'iso2'     => 'SR',
            'iso3'     => 'SUR',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'SRD',
                'name'   => 'Surinamese dollar',
                'native' => 'Surinaamse dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Svalbard and Jan Mayen — Svalbard og Jan Mayen',
            'iso2'     => 'SJ',
            'iso3'     => 'SJM',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'NOK',
                'name'   => 'Norwegian Krone',
                'native' => 'Norwegian Krone',
                'symbol' => 'kr',
            ],
        ],
        [
            'name'     => 'Sweden — Sverige',
            'iso2'     => 'SE',
            'iso3'     => 'SWE',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'SEK',
                'name'   => 'Swedish krona',
                'native' => 'Svensk krona',
                'symbol' => 'kr',
            ],
        ],
        [
            'name'     => 'Switzerland — Schweiz',
            'iso2'     => 'CH',
            'iso3'     => 'CHE',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'CHF',
                'name'   => 'Swiss franc',
                'native' => 'Schweizer Franken',
                'symbol' => 'CHf',
            ],
        ],
        [
            'name'     => 'Syria — سوريا',
            'iso2'     => 'SY',
            'iso3'     => 'SYR',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'SYP',
                'name'   => 'Syrian pound',
                'native' => 'ليرة سورية',
                'symbol' => 'LS',
            ],
        ],
        [
            'name'     => 'Taiwan — 臺灣',
            'iso2'     => 'TW',
            'iso3'     => 'TWN',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'TWD',
                'name'   => 'New Taiwan dollar',
                'native' => '新台幣',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Tajikistan — Тоҷикистон',
            'iso2'     => 'TJ',
            'iso3'     => 'TJK',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'TJS',
                'name'   => 'Tajikistani somoni',
                'native' => 'Сомонӣ',
                'symbol' => 'SM',
            ],
        ],
        [
            'name'     => 'Tanzania — Tanzania',
            'iso2'     => 'TZ',
            'iso3'     => 'TZA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'TZS',
                'name'   => 'Tanzanian shilling',
                'native' => 'Shilingi ya Tanzania',
                'symbol' => 'TSh',
            ],
        ],
        [
            'name'     => 'Thailand — ประเทศไทย',
            'iso2'     => 'TH',
            'iso3'     => 'THA',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'THB',
                'name'   => 'Thai baht',
                'native' => 'บาท',
                'symbol' => '฿',
            ],
        ],
        [
            'name'     => 'Timor-Leste — Timor-Leste',
            'iso2'     => 'TL',
            'iso3'     => 'TLS',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'Dólar americano',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Togo — Togo',
            'iso2'     => 'TG',
            'iso3'     => 'TGO',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'XOF',
                'name'   => 'West African CFA franc',
                'native' => 'Franc CFA (BCEAO)',
                'symbol' => 'CFA',
            ],
        ],
        [
            'name'     => 'Tokelau — Tokelau',
            'iso2'     => 'TK',
            'iso3'     => 'TKL',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'NZD',
                'name'   => 'New Zealand dollar',
                'native' => 'New Zealand Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Tonga — Tonga',
            'iso2'     => 'TO',
            'iso3'     => 'TON',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'TOP',
                'name'   => 'Tongan paʻanga',
                'native' => 'Paʻanga fakatonga',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Trinidad and Tobago — Trinidad and Tobago',
            'iso2'     => 'TT',
            'iso3'     => 'TTO',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'TTD',
                'name'   => 'Trinidad and Tobago dollar',
                'native' => 'Trinidad & Tobago Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Tunisia — تونس',
            'iso2'     => 'TN',
            'iso3'     => 'TUN',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'TND',
                'name'   => 'Tunisian dinar',
                'native' => 'دينار تونسي',
                'symbol' => 'ت.د',
            ],
        ],
        [
            'name'     => 'Türkiye — Türkiye',
            'iso2'     => 'TR',
            'iso3'     => 'TUR',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'TRY',
                'name'   => 'Turkish lira',
                'native' => 'Türk lirası',
                'symbol' => '₺',
            ],
        ],
        [
            'name'     => 'Turkmenistan — Türkmenistan',
            'iso2'     => 'TM',
            'iso3'     => 'TKM',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'TMT',
                'name'   => 'Turkmenistan manat',
                'native' => 'Türkmen manady',
                'symbol' => 'T',
            ],
        ],
        [
            'name'     => 'Turks and Caicos Islands — Turks and Caicos Islands',
            'iso2'     => 'TC',
            'iso3'     => 'TCA',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Tuvalu — Tuvalu',
            'iso2'     => 'TV',
            'iso3'     => 'TUV',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'AUD',
                'name'   => 'Australian dollar',
                'native' => 'Australian Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'U.S. Virgin Islands — United States Virgin Islands',
            'iso2'     => 'VI',
            'iso3'     => 'VIR',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Uganda — Uganda',
            'iso2'     => 'UG',
            'iso3'     => 'UGA',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'UGX',
                'name'   => 'Ugandan shilling',
                'native' => 'Ugandan Shilling',
                'symbol' => 'USh',
            ],
        ],
        [
            'name'     => 'Ukraine — Україна',
            'iso2'     => 'UA',
            'iso3'     => 'UKR',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'UAH',
                'name'   => 'Ukrainian hryvnia',
                'native' => 'Українська гривня',
                'symbol' => '₴',
            ],
        ],
        [
            'name'     => 'United Arab Emirates — دولة الإمارات العربية المتحدة',
            'iso2'     => 'AE',
            'iso3'     => 'ARE',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'AED',
                'name'   => 'United Arab Emirates dirham',
                'native' => 'درهم إماراتي',
                'symbol' => 'إ.د',
            ],
        ],
        [
            'name'     => 'United Kingdom — United Kingdom',
            'iso2'     => 'GB',
            'iso3'     => 'GBR',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'GBP',
                'name'   => 'British pound',
                'native' => 'British Pound',
                'symbol' => '£',
            ],
        ],
        [
            'name'     => 'United States — United States',
            'iso2'     => 'US',
            'iso3'     => 'USA',
            'region'   => 'NA',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'United States Minor Outlying Islands — United States Minor Outlying Islands',
            'iso2'     => 'UM',
            'iso3'     => 'UMI',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'USD',
                'name'   => 'United States dollar',
                'native' => 'US Dollar',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Uruguay — Uruguay',
            'iso2'     => 'UY',
            'iso3'     => 'URY',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'UYU',
                'name'   => 'Uruguayan peso',
                'native' => 'Peso uruguayo',
                'symbol' => '$',
            ],
        ],
        [
            'name'     => 'Uzbekistan — Oʻzbekiston',
            'iso2'     => 'UZ',
            'iso3'     => 'UZB',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'UZS',
                'name'   => 'Uzbekistani soʻm',
                'native' => 'Oʻzbekiston soʻmi',
                'symbol' => 'лв',
            ],
        ],
        [
            'name'     => 'Vanuatu — Vanuatu',
            'iso2'     => 'VU',
            'iso3'     => 'VUT',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'VUV',
                'name'   => 'Vanuatu vatu',
                'native' => 'Vanuatu Vatu',
                'symbol' => 'VT',
            ],
        ],
        [
            'name'     => 'Vatican City — Città del Vaticano',
            'iso2'     => 'VA',
            'iso3'     => 'VAT',
            'region'   => 'EU',
            'currency' => [
                'code'   => 'EUR',
                'name'   => 'Euro',
                'native' => 'Euro',
                'symbol' => '€',
            ],
        ],
        [
            'name'     => 'Venezuela — Venezuela',
            'iso2'     => 'VE',
            'iso3'     => 'VEN',
            'region'   => 'SA',
            'currency' => [
                'code'   => 'VES',
                'name'   => 'Venezuelan bolívar',
                'native' => 'Bolívar soberano',
                'symbol' => 'Bs.',
            ],
        ],
        [
            'name'     => 'Vietnam — Việt Nam',
            'iso2'     => 'VN',
            'iso3'     => 'VNM',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'VND',
                'name'   => 'Vietnamese đồng',
                'native' => 'Đồng Việt Nam',
                'symbol' => '₫',
            ],
        ],
        [
            'name'     => 'Wallis and Futuna — Wallis-et-Futuna',
            'iso2'     => 'WF',
            'iso3'     => 'WLF',
            'region'   => 'OC',
            'currency' => [
                'code'   => 'XPF',
                'name'   => 'CFP franc',
                'native' => 'Franc CFP',
                'symbol' => '₣',
            ],
        ],
        [
            'name'     => 'Western Sahara — الصحراء الغربية',
            'iso2'     => 'EH',
            'iso3'     => 'ESH',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'MAD',
                'name'   => 'Moroccan Dirham',
                'native' => 'درهم مغربي',
                'symbol' => 'MAD',
            ],
        ],
        [
            'name'     => 'Yemen — اليمن',
            'iso2'     => 'YE',
            'iso3'     => 'YEM',
            'region'   => 'AS',
            'currency' => [
                'code'   => 'YER',
                'name'   => 'Yemeni rial',
                'native' => 'ريال يمني',
                'symbol' => '﷼',
            ],
        ],
        [
            'name'     => 'Zambia — Zambia',
            'iso2'     => 'ZM',
            'iso3'     => 'ZMB',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'ZMW',
                'name'   => 'Zambian kwacha',
                'native' => 'Zambian Kwacha',
                'symbol' => 'ZK',
            ],
        ],
        [
            'name'     => 'Zimbabwe — Zimbabwe',
            'iso2'     => 'ZW',
            'iso3'     => 'ZWE',
            'region'   => 'AF',
            'currency' => [
                'code'   => 'ZWG',
                'name'   => 'Zimbabwe Gold',
                'native' => 'Zimbabwe Gold',
                'symbol' => 'ZiG',
            ],
        ],
    ];

    /**
     * Get the countries: `name`, `iso2`, `iso3`, `region` and `currency` with `code`, `name`,
     * `native` and `symbol`.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function all(): array
    {
        return self::COUNTRIES;
    }
}
