#!/usr/bin/env php
<?php
const EX_PATH                   = __DIR__ . '/';
const EX_VERSION                = '2025.1';
const EX_REQUIRED_PHP_VERSION   = '8.2';
const EX_REQUIRED_MYSQL_VERSION = '8.0';

require_once __DIR__ . '/env.php';
require_once __DIR__ . '/autoload.php';

use Expansa\Console\Terminal;

$console = new Terminal();
$console->handle();
