<?php

/**
 * Settings of the installation, written by the installer. Real environment variables (Docker, CI, a hosting panel)
 * override EX_DB_*, EX_KEY_* and EX_DEBUG; an empty variable counts as not set. EX_MAIL is set in the installer.
 */

/**
 * Database connection, passed to Db::configure() as named arguments.
 *
 * @since 2025.1
 */
define('EX_DB', [
    'driver'     => getenv('EX_DB_DRIVER') ?: 'mysql',
    'database'   => getenv('EX_DB_NAME') ?: 'db.name',
    'username'   => getenv('EX_DB_USERNAME') ?: 'db.username',
    'password'   => getenv('EX_DB_PASSWORD') ?: 'db.password',
    'host'       => getenv('EX_DB_HOST') ?: 'db.host',
    'prefix'     => getenv('EX_DB_PREFIX') ?: 'db.prefix',
    'charset'    => 'utf8mb4',
    'collation'  => 'utf8mb4_general_ci',
    'port'       => (int) (getenv('EX_DB_PORT') ?: 3306),
    // keeps the connection open between requests served by the same PHP worker
    'persistent' => false,
    // keep every query for Db::log(), not only the last one; disabled by default for better performance
    'logging'    => false,
    // PDO::ERRMODE_SILENT (default) | PDO::ERRMODE_WARNING | PDO::ERRMODE_EXCEPTION, see https://www.php.net/manual/en/pdo.error-handling.php
    'error'      => PDO::ERRMODE_SILENT,
]);

/**
 * Cache stores, passed to Cache::configure(). `default` serves Cache::get() and the other facade methods,
 * Cache::store('name') picks another one. EX_CACHE_STORE overrides the default.
 *
 * @since 2025.6
 */
define('EX_CACHE', [
    'default' => getenv('EX_CACHE_STORE') ?: 'memory',
    'stores'  => [
        // the current request only, needs nothing
        'memory'    => ['driver' => 'memory'],
        // files on disk, survive between requests
        'file'      => ['driver' => 'file', 'path' => EX_STORAGE . 'cache'],
        // shared memory of the PHP process, needs ext-apcu
        'apcu'      => ['driver' => 'apcu'],
        // needs ext-redis
        'redis'     => [
            'driver' => 'redis',
            'host'   => getenv('EX_REDIS_HOST') ?: '127.0.0.1',
            'port'   => (int) (getenv('EX_REDIS_PORT') ?: 6379),
        ],
        // needs ext-memcached; servers: [host, port, weight]
        'memcached' => ['driver' => 'memcached', 'servers' => [['127.0.0.1', 11211]]],
        // the "cache" table of the site database
        'database'  => ['driver' => 'database'],
    ],
]);

/**
 * Keys for signing cookies and tokens, generated by the installer.
 * Changing them invalidates every existing cookie, so all users have to sign in again.
 *
 * @since 2025.1
 */
define('EX_KEYS', [
    'auth'  => getenv('EX_KEY_AUTH') ?: 'auth.key',
    'nonce' => getenv('EX_KEY_NONCE') ?: 'nonce.key',
    'hash'  => getenv('EX_KEY_HASH') ?: 'hash.key',
]);

/**
 * Debug mode: errors on the page and the debug view with the code around them. Never enable it on a public site.
 *
 * @since 2025.1
 */
define('EX_DEBUG', [
    // EX_DEBUG=1, true or on enables it
    'enabled' => filter_var(getenv('EX_DEBUG'), FILTER_VALIDATE_BOOL),
    // uncaught errors go to the log
    'log'     => true,
    'view'    => EX_DASHBOARD . 'debug.php',
    // links from the error page to the code: vscode://file/{file}:{line}, phpstorm://open?file={file}&line={line}
    'editor'  => getenv('EX_DEBUG_EDITOR') ?: '',
]);

/**
 * SMTP settings for outgoing mail.
 *
 * @since 2025.1
 */
define('EX_MAIL', [
    'host'     => 'smtp.host',
    'port'     => (int) 'smtp.port',
    'username' => 'smtp.username',
    'password' => 'smtp.password',
    'from'     => 'smtp.from',
]);

/**
 * DKIM (DomainKeys Identified Mail) settings for signing outgoing emails.
 *
 * @since 2025.1
 */
define('EX_DKIM', [
    // signing domain, typically the domain of the 'From' address
    'domain'           => '',
    // path to the private key
    'private'          => '',
    // selector of the DNS record with the public key
    'selector'         => '',
    // passphrase of the private key, if any
    'passphrase'       => '',
    // signing identity, typically the 'From' address
    'identity'         => '',
    // include the signed header fields in the signature
    'copyHeaderFields' => false,
    // extra headers to sign
    'extraHeaders'     => ['List-Unsubscribe', 'List-Help'],
]);

/**
 * AI service for generating plugins: any OpenAI-compatible Chat Completions API.
 * Free for testing: Google Gemini (a key from aistudio.google.com) with the defaults below, or OpenRouter:
 * EX_AI_URL=https://openrouter.ai/api/v1/, EX_AI_MODEL=<model id ending in :free>, EX_AI_KEY=<openrouter key>.
 *
 * @since 2026.10
 */
define('EX_AI', [
    'url'     => getenv('EX_AI_URL') ?: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    'model'   => getenv('EX_AI_MODEL') ?: 'gemini-flash-latest',
    'key'     => getenv('EX_AI_KEY') ?: '',
    // false for models without json_schema structured output: the schema goes into the instructions
    'schemas' => filter_var(getenv('EX_AI_SCHEMAS') ?: 'on', FILTER_VALIDATE_BOOL),
    // extra request fields, e.g. ['reasoning_effort' => 'low']
    'options' => [],
    // reference material for the model: Markdown files of the CMS documentation
    'context' => getenv('EX_AI_CONTEXT') ?: dirname(EX_PATH) . '/documentation',
    // PHP CLI binary for the background worker; under PHP-FPM PHP_BINARY is the FPM binary
    'php'     => getenv('EX_AI_PHP') ?: PHP_BINARY,
]);
