<?php
/**
 * Database connection, passed to Db::configure() as named arguments.
 *
 * @since 2025.1
 */
const EX_DB = [
    'driver'     => 'mysql',
    'database'   => 'db.name',
    'username'   => 'db.username',
    'password'   => 'db.password',
    'host'       => 'db.host',
    'prefix'     => 'db.prefix',
    'charset'    => 'utf8mb4',
    'collation'  => 'utf8mb4_general_ci',
    'port'       => 3306,
    // keeps the connection open between requests served by the same PHP worker
    'persistent' => false,
    // keep every query for Db::log(), not only the last one; disabled by default for better performance
    'logging'    => false,
    // PDO::ERRMODE_SILENT (default) | PDO::ERRMODE_WARNING | PDO::ERRMODE_EXCEPTION, see https://www.php.net/manual/en/pdo.error-handling.php
    'error'      => PDO::ERRMODE_SILENT,
];

/**
 * Keys for signing cookies and tokens, generated by the installer.
 * Changing them invalidates every existing cookie, so all users have to sign in again.
 *
 * @since 2025.1
 */
const EX_KEYS = [
    'auth'  => 'auth.key',
    'nonce' => 'nonce.key',
    'hash'  => 'hash.key',
];

/**
 * Debug mode: errors on the page and the debug view with the code around them. Never enable it on a public site.
 *
 * @since 2025.1
 */
const EX_DEBUG = [
    'enabled' => false,
    'log'     => true,
    'view'    => EX_DASHBOARD . 'debug.php',
];

/**
 * DKIM (DomainKeys Identified Mail) settings for signing outgoing emails.
 *
 * @since 2025.1
 */
const EX_DKIM = [
    // signing domain, typically the domain of the 'From' address
    'domain'           => 'example.com',
    // path to the private key
    'private'          => 'dkim_private.pem',
    // selector of the DNS record with the public key
    'selector'         => 'phpmailer',
    // passphrase of the private key, if any
    'passphrase'       => '',
    // signing identity, typically the 'From' address
    'identity'         => '',
    // include the signed header fields in the signature
    'copyHeaderFields' => false,
    // extra headers to sign
    'extraHeaders'     => ['List-Unsubscribe', 'List-Help'],
];
