<?php
/**
 * Settings of the installation, written by the installer. Real environment variables (Docker, CI, a hosting panel)
 * override the values: EX_DB_*, EX_KEY_* and EX_DEBUG; an empty variable counts as not set.
 */

/**
 * Database connection, passed to Db::configure() as named arguments.
 *
 * @since 2025.1
 */
define('EX_DB', [
    'driver'     => getenv('EX_DB_DRIVER') ?: 'mysql',
    'database'   => getenv('EX_DB_NAME') ?: 'db.name',
    'username'   => getenv('EX_DB_USERNAME') ?: 'db.username',
    'password'   => getenv('EX_DB_PASSWORD') ?: 'db.password',
    'host'       => getenv('EX_DB_HOST') ?: 'db.host',
    'prefix'     => getenv('EX_DB_PREFIX') ?: 'db.prefix',
    'charset'    => 'utf8mb4',
    'collation'  => 'utf8mb4_general_ci',
    'port'       => (int) (getenv('EX_DB_PORT') ?: 3306),
    // keeps the connection open between requests served by the same PHP worker
    'persistent' => false,
    // keep every query for Db::log(), not only the last one; disabled by default for better performance
    'logging'    => false,
    // PDO::ERRMODE_SILENT (default) | PDO::ERRMODE_WARNING | PDO::ERRMODE_EXCEPTION, see https://www.php.net/manual/en/pdo.error-handling.php
    'error'      => PDO::ERRMODE_SILENT,
]);

/**
 * Keys for signing cookies and tokens, generated by the installer.
 * Changing them invalidates every existing cookie, so all users have to sign in again.
 *
 * @since 2025.1
 */
define('EX_KEYS', [
    'auth'  => getenv('EX_KEY_AUTH') ?: 'auth.key',
    'nonce' => getenv('EX_KEY_NONCE') ?: 'nonce.key',
    'hash'  => getenv('EX_KEY_HASH') ?: 'hash.key',
]);

/**
 * Debug mode: errors on the page and the debug view with the code around them. Never enable it on a public site.
 *
 * @since 2025.1
 */
define('EX_DEBUG', [
    // EX_DEBUG=1, true or on enables it
    'enabled' => filter_var(getenv('EX_DEBUG'), FILTER_VALIDATE_BOOL),
    'log'     => true,
    'view'    => EX_DASHBOARD . 'debug.php',
]);

/**
 * DKIM (DomainKeys Identified Mail) settings for signing outgoing emails.
 *
 * @since 2025.1
 */
define('EX_DKIM', [
    // signing domain, typically the domain of the 'From' address
    'domain'           => 'example.com',
    // path to the private key
    'private'          => 'dkim_private.pem',
    // selector of the DNS record with the public key
    'selector'         => 'phpmailer',
    // passphrase of the private key, if any
    'passphrase'       => '',
    // signing identity, typically the 'From' address
    'identity'         => '',
    // include the signed header fields in the signature
    'copyHeaderFields' => false,
    // extra headers to sign
    'extraHeaders'     => ['List-Unsubscribe', 'List-Help'],
]);
